name: test command
on: [push]
jobs:

  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf /home/ec2-user/test
            git clone https://github.com/Brat2Sumy/test.git /home/ec2-user/test
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker build -t backend /home/ec2-user/test
            docker run -p 3000:3000 -td backend
            docker update --restart unless-stopped $(docker ps -a -q)
