name: test command
on: [push]
jobs:

  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Use script
        uses: vargiuscuola/gen-sh-unittest@v1.0
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          run: /home/ec2-user/manual_deploy.sh
