name: test command
on: [push]
jobs:

  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - neme: Use script
        uses: bewuethr/shellcheck-action@v2.1.2
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          run: /home/ec2-user/manual_deploy.sh
