name: test command
on: [push]
jobs:

  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            export APP_PORT=3000
            export DB_USER=postgres
            export DB_HOST=11.0.1.184
            export DB_NAME=ops_test
            export DB_PASSWORD=qwerty
            export DB_PORT=5432
            npm run start
