name: test command
on: [push]
jobs:

  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: appleboy/ssh-action@master
        with:
          host: "34.218.157.111:22"
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: whoami
